import {
    anitaImg,
    borisImg,
    davidImg, ethanImg, harveyImg, jackImg, johnImg, jollyImg, maryImg, resImg, saymourImg, tammyImg, taylorImg, teddImg, tonyImg
} from "./assets";


const data = [
    {
        image: [taylorImg],
        name: "Taylor Sift",
        address: "London, United Kingdom",
        email: "taylor.sift@outlook.com",
        phone: "44 2258 257 021",
        linkedin: "linkedin.com/taylor-sift",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [saymourImg],
        name: "Seymour Cevees",
        address: "United Kingdom",
        email: "taylor@outlook.com",
        phone: "44 546 547 021",
        linkedin: "linkedin.com/taylor",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [resImg],
        name: "Res Hugh May",
        address: "London, Pakistan",
        email: "sift@outlook.com",
        phone: "89 89089 257 021",
        linkedin: "linkedin.com/taylorsift",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [jackImg],
        name: "Jack Reacher",
        address: "Fsd, United Land",
        email: "test@outlook.com",
        phone: "454 3445 257 021",
        linkedin: "linkedin.com/taysas",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [ethanImg],
        name: "Ethan Hunt",
        address: "United Kingdom",
        email: "taylor@outlook.com",
        phone: "44 546 547 021",
        linkedin: "linkedin.com/taylor",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [johnImg],
        name: "John Doe",
        address: "London, United Kingdom",
        email: "taylor.sift@outlook.com",
        phone: "44 2258 257 021",
        linkedin: "linkedin.com/taylor-sift",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [maryImg],
        name: "Mary Poppins",
        address: "London, Pakistan",
        email: "sift@outlook.com",
        phone: "89 89089 257 021",
        linkedin: "linkedin.com/taylorsift",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [borisImg],
        name: "Boris Blade",
        address: "Fsd, United Land",
        email: "test@outlook.com",
        phone: "454 3445 257 021",
        linkedin: "linkedin.com/taysas",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [anitaImg],
        name: "Anita Bath",
        address: "United Kingdom",
        email: "taylor@outlook.com",
        phone: "44 546 547 021",
        linkedin: "linkedin.com/taylor",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [davidImg],
        name: "David White",
        address: "London, United Kingdom",
        email: "taylor.sift@outlook.com",
        phone: "44 2258 257 021",
        linkedin: "linkedin.com/taylor-sift",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [tonyImg],
        name: "Tony Bird",
        address: "London, Pakistan",
        email: "sift@outlook.com",
        phone: "89 89089 257 021",
        linkedin: "linkedin.com/taylorsift",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [teddImg],
        name: "Ted Baker",
        address: "Fsd, United Land",
        email: "test@outlook.com",
        phone: "454 3445 257 021",
        linkedin: "linkedin.com/taysas",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [tammyImg],
        name: "Tammy Turner",
        address: "United Kingdom",
        email: "taylor@outlook.com",
        phone: "44 546 547 021",
        linkedin: "linkedin.com/taylor",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
    {
        image: [jollyImg],
        name: "Angelina Jolly",
        address: "London, United Kingdom",
        email: "taylor.sift@outlook.com",
        phone: "44 2258 257 021",
        linkedin: "linkedin.com/taylor-sift",
        role1: "UX Design",
        role2: "Laravel",
        role3: "Node JS",
        quali1: "Msc",
        quali2: "Deploma",
        quali3: "ADP",
        ques1: "Hello",
        ques2: "Tests",
        ques3: "Demo",
    },
    {
        image: [harveyImg],
        name: "Harvey Lewis",
        address: "London, Pakistan",
        email: "sift@outlook.com",
        phone: "89 89089 257 021",
        linkedin: "linkedin.com/taylorsift",
        role1: "Data science",
        role2: "Frontend",
        role3: "Backend",
        quali1: "Matric",
        quali2: "Fsc",
        quali3: "Bsc",
        ques1: "Working",
        ques2: "Rights",
        ques3: "portfolio",
    },
]

export default data;